### ISSUE TITLE
default boudingbox should come from config

### ISSUE THREAD

**Issue by FranckErnewein** [lightstream-company/velomagg#20]
the map should be center on the current city.
this setting should come from config file.

config file should contains the city bounding box instead of the center.
leaflet can calculate the most adpated zoom

We should use 
```js
map.panInsideBounds(city_boundingbox)
```

instead of 

```js
map.setView(city_center, 13);
```

**Comment by rehia** [comment]
Add this in config/public.json
```
"bounding_box": {
    "south_west": [3.704, 43.523],
    "north_east": [4.056, 43.686]
  }
```
